#include <stdio.h>
#include <math.h>
int main(void)
{
    int dia0, mes0, ano0, dia, mes, ano, iddia, idmes, idano;
    float t, t1, t2, a, b, c;
    float ovos, terra, po, bichos, noxo, peidos, andar, luz, sol, parpadeos,
    atomos, pelos, cuaderno[2], pop, imaxes, sonhos, auga, latidos, costelas,
    raios, risa, casas, terremotos, sudor, mocos, caracois, mcdonalds, pelo;
    printf("\nEste programa dache datos curiosos sobre a tua vida");
    printf("\nbaseados en estatisticas. Estas listo/a?\n");
    printf("\n");
    system("pause");
    printf("\nIntroduce a tua data de nacemento en formato dia mes ano\n");
    scanf("%d %d %d",&dia0,&mes0,&ano0);
    t1=(ano0*365.25+mes0*30.4167+dia0)*24.0*3600.0;
    printf("\nAgora a data actual:\n");
    scanf("%d %d %d",&dia,&mes,&ano);
    t2=(ano*365.25+mes*30.4167+dia)*24.0*3600.0;
    t=t2-t1;
    a=t/365.25/24.0/3600.0;
    b=a-floor(a);
    idano=(int)floor(a);
    b*=12.0;
    c=b-floor(b);
    idmes=(int)floor(b);
    c*=30.4167;
    iddia=(int)floor(c);
    ovos=19*12*a;
    terra=107118*24*365.25*a;
    po=11000*a;
    bichos=14.0*a;
    noxo=6*a;
    peidos=365.25*1*a;
    andar=4.5*365.25*24*a;
    luz=t*299792.458;
    sol=377*t;
    parpadeos=25000*365.25*a/7.0;
    atomos=pow(2.0,a)*pow(100.0,-b/12.0);
    pelos=100*365.25*a;
    cuaderno[1]=8*a;
    cuaderno[2]=cuaderno[1]/3.0;
    pop=t/6.0;
    imaxes=2*t/(3.0*0.00015);
    sonhos=1460*a;
    auga=0.126*a;
    latidos=(130+85*9+80*(float)(idano-10))*60*24*365.25;
    costelas=5*a;
    raios=1000*t;
    risa=15*365.25*a;
    casas=t/45.0;
    terremotos=50000*a;
    sudor=3.7854118*365.25*a;
    mocos=0.25*365.25*a;
    caracois=500*a;
    mcdonalds=3*a;
    pelo=0.000254*365.25*a;
    printf("\nLevas vividos %f segundos\n", t);
    printf("\nLevas vividos %i anos %i meses e %i dias. Nese tempo:\n", idano, idmes, iddia);
    printf("\nUnha galinha teria posto uns %.0f ovos\n", ovos);
    printf("\nA Terra moveuse uns %.0f km\n", terra);
    printf("\nCaeron unhas %.0f toneladas de po interplanetario na Terra\n", po);
    printf("\nComiches uns %.0f insectos mentres durmias\n",bichos);
    printf("\nDecheslle a man a uns %.0f tios que non se lavaron as mans\n",noxo);
    printf("\nInhalaches uns %.0f litros de peidos\n",peidos);
    printf("\nSe comezaras a andar e non pararas terias recorridos %.0f km\n", andar);
    printf("\nA luz viaxou uns %.2f anos luz que son uns %.0f km\n",a,luz);
    printf("\nO sol radiou uns %.0f YJ \n",sol);
    printf("\nParpadeaches unhas %.0f veces\n",parpadeos);
    printf("\n %.0f x 10^-%i e a probabilidade de cada atomo que tes non fose substituido\n",atomos,2*idano);
    printf("\nPerdeches uns %.0f pelos\n",pelos);
    printf("\nUn alumno gastaria uns %.0f cuadernos que equivalen a uns %.0f arbores\n",cuaderno[1],cuaderno[2]);
    printf("\nProducironse unhas %.0f cancions de pop\n",pop);
    printf("\nProcesaches unhas %.0f imaxes\n",imaxes);
    printf("\nTiveches uns %.0f sonhos\n",sonhos);
    printf("\nConsumironse uns %.3f billons de litros en auga embotellada\n",auga);
    printf("\nO teu corazon latiu unhas %.0f veces\n",latidos);
    printf("\nAs costelas moveronseche uns %.0f millons de veces\n",costelas);
    printf("\nCaeron uns %.0f raios\n",raios);
    printf("\nRicheste unhas %.0f veces\n",risa);
    printf("\nArderon unhas %.0f casas\n",casas);
    printf("\nHoubo uns %.0f terremotos\n",terremotos);
    printf("\nSudaches uns %.0f litros\n",casas);
    printf("\nTragaches uns %.0f litros de mocos\n",mocos);
    printf("\nUn francés teria comido uns %.0f caracois\n",caracois);
    printf("\nMcDonalds vendiu uns %.0f mil millons de hamburguesas\n",mcdonalds);
    printf("\nO teu pelo medrou uns %.3f metros\n",pelo);
    printf("\n");
    system("pause");
    return 0;
}
